Cardstone/Cardstone.Web/Controllers/GameControllers/GameController.cs
using Cardstone.Data.Models;
using Cardstone.Services.Contracts;
using Cardstone.Web.Models;
using Cardstone.Web.Models.DeckViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Cardstone.Web.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly IPlayerService _playerService;
        private readonly ICardService _cardService;
        private readonly UserManager<Player> _userManager;

        public GameController(IPlayerService playerService, ICardService cardService, UserManager<Player> userManager)
        {
            this._cardService = cardService;
            this._playerService = playerService;
            this._userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var players = this._playerService
                .GetPlayers()
                .Select(p => 
                {
                    return new PlayerViewModel
                    {
                        AvatarURL = p.AvatarImageName,
                        Username = p.UserName,
                        XP = p.XP
                    };
                })
                .Take(10);

            return View(players);
        }


        [HttpGet]
        public IActionResult Deck(DeckViewModel model)
        {
            var currentUser = HttpContext.User.Identity.Name;
            var playerCards = this._playerService.GetPlayerCards(currentUser);

            model.PlayersCards = playerCards;

            return View(model);
        }

        [HttpGet]
        public IActionResult Battle()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Leaderboard()
        {
            var players = this._playerService
                .GetPlayers()
                .Select(p =>
                {
                    return new PlayerViewModel
                    {
                        AvatarURL = p.AvatarImageName,
                        Username = p.UserName,
                        XP = p.XP
                    };
                })
                .OrderByDescending(p => p.XP)
                .Take(100);

            return View(players);
        }
    }
}

Cardstone/Cardstone.Web/Controllers/StoreControllers/StoreController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Cardstone.Data.Exceptions;
using Cardstone.Data.Models;
using Cardstone.Services.Contracts;
using Cardstone.Web.Models.StoreViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace Cardstone.Web.Controllers.StoreControllers
{
    public class StoreController : Controller
    {
        private readonly UserManager<Player> _userManager;
        private readonly ICardService _cardService;
        private readonly IPurchaseService _purchaseService;

        public StoreController(UserManager<Player> userManager,
                               ICardService cardService,
                               IPurchaseService purchaseService)
        {
            this._userManager = userManager;
            this._cardService = cardService;
            this._purchaseService = purchaseService;
        }

        [HttpGet]
        [Authorize]
        public IActionResult Store(StoreViewModel model)
        {
            var singedUser = HttpContext.User.Identity.Name;
            var cards = this._cardService.GetStoreCards(singedUser);

            model.Cards = cards;

            return View(model);
        }

        [HttpGet]
        [Authorize]
        public IActionResult Buy(string cardName)
        {
            var singedUser = HttpContext.User.Identity.Name;
            try
            {
                _purchaseService.PurchaseCard(singedUser, cardName);
            }
            catch (NotEnoughCoinsException ex)
            {
                return PartialView("_PartialModal", ex.Message);
            }
            

            return this.RedirectToAction("Deck", "Game");
        }
    }
}

Cardstone/Cardstone.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cardstone</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <span> <img class="navbar-icon" src="https://i.pinimg.com/originals/ff/75/86/ff7586e945387adcd71f94fadbc87a13.png" alt="Logo" /></span>
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; CardstoneProject</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Cardstone/Cardstone.Web/Views/Shared/_PartialModal.cshtml
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Purchasing Card</h4>
            </div>
            <div class="modal-body">
                <p>You have unsufficient funds!</p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            </div>
        </div>

Cardstone/Cardstone.Web/Views/Shared/_SignedInLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Cardstone</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <a asp-area="" asp-controller="Home" asp-action="Index">
                    <span><img class="navbar-icon" src="https://i.pinimg.com/originals/ff/75/86/ff7586e945387adcd71f94fadbc87a13.png" alt="Logo" /></span>
                </a>
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Game" asp-action="Index">Play</a></li>
                    <li><a asp-area="" asp-controller="Game" asp-action="Deck">Deck</a></li>
                    <li><a asp-area="" asp-controller="Store" asp-action="Store">Store</a></li>
                    <li><a asp-area="" asp-controller="Game" asp-action="Leaderboard">Leaderboard</a></li>
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; CardstoneProject</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>