Cardstone/Cardstone.Web/Models/DeckViewModels/DeckViewModel.cs
using Cardstone.Data.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Cardstone.Web.Models.DeckViewModels
{
    public class DeckViewModel
    {
        public IEnumerable<PlayersCards> PlayersCards { get; set; }        
    }
}

Cardstone/Cardstone.Web/Controllers/GameControllers/GameController.cs
using Cardstone.Data.Models;
using Cardstone.Services.Contracts;
using Cardstone.Web.Models;
using Cardstone.Web.Models.DeckViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;

namespace Cardstone.Web.Controllers
{
    [Authorize]
    public class GameController : Controller
    {
        private readonly IPlayerService _playerService;
        private readonly ICardService _cardService;
        private readonly UserManager<Player> _userManager;

        public GameController(IPlayerService playerService, ICardService cardService, UserManager<Player> userManager)
        {
            this._cardService = cardService;
            this._playerService = playerService;
            this._userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            var players = this._playerService
                .GetPlayers()
                .Select(p => 
                {
                    return new PlayerViewModel
                    {
                        AvatarURL = p.AvatarImageName,
                        Username = p.UserName,
                        XP = p.XP
                    };
                })
                .Take(10);

            return View(players);
        }


        [HttpGet]
        public IActionResult Deck(DeckViewModel model)
        {
            var currentUser = HttpContext.User.Identity.Name;
            var playerCards = this._playerService.GetPlayerCards(currentUser);

            model.PlayersCards = playerCards;

            return View(model);
        }

        [HttpGet]
        public IActionResult Battle()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Leaderboard()
        {
            var players = this._playerService
                .GetPlayers()
                .Select(p =>
                {
                    return new PlayerViewModel
                    {
                        AvatarURL = p.AvatarImageName,
                        Username = p.UserName,
                        XP = p.XP
                    };
                })
                .OrderByDescending(p => p.XP)
                .Take(100);

            return View(players);
        }
    }
}

Cardstone/Cardstone.Web/Views/Game/Deck.cshtml
@using Cardstone.Web.Models.DeckViewModels
@model DeckViewModel

@{
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";

}

@{
    ViewData["Title"] = "Deck";
}

<h1 class="main-title">My Cards</h1>

<div class="card-container">
    @foreach (var playerCard in Model.PlayersCards)
    {
        <div class="card flip-card" style="width: 18rem;">
            <div class="flip-card-inner">
                <div class="flip-card-front">
                    <img class="card-image" src="@playerCard.Card.ImageURL">
                    <h5 class="card-title">@playerCard.Card.Name</h5>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">Attack: <strong>@playerCard.Card.Attack</strong></li>
                        <li class="list-group-item">Armor: <strong>@playerCard.Card.Armor</strong></li>
                    </ul>
                </div>
                <div class="flip-card-back">
                    <img src="https://i.pinimg.com/originals/8a/10/8a/8a108a478f3f25158750cdedc4001370.png" style="width:100%">
                    <div class="card-description">
                        <h4>Description</h4>
                        <hr />
                        <p class="card-text">The card descritpion</p>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

Cardstone/Cardstone.Web/Views/Game/Index.cshtml
@model IEnumerable<PlayerViewModel>

@{
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";
}

@{
    ViewData["Title"] = "Play";
}

<h1 class="main-title">Play</h1>

<table class="table table-condensed table-hover">
    <tr>
        <th>Avatar</th>
        <th>Username</th>
        <th>Experience Points</th>
        <th>Challenge</th>
    </tr>
    @foreach (var player in Model)
    {
        <tr>
            <td><img class="mini-avatar" src="@player.AvatarURL" /></td>
            <td>@player.Username</td>
            <td>@player.XP</td>
            <td><button class="btn btn-success" type="button" asp-area="" asp-controller="Game" asp-action="Battle">Battle!</button></td>
        </tr>
    }
</table>

Cardstone/Cardstone.Web/Views/Game/Leaderboard.cshtml
@model IEnumerable<PlayerViewModel>

@{
    Layout = "~/Views/Shared/_SignedInLayout.cshtml";
}

@{
    ViewData["Title"] = "Leaderboard";
}

<h1 class="main-title">Leaderboard</h1>

<td><button type="button" class="btn btn-primary" asp-area="" asp-controller="Game" asp-action="Leaderboard">Where I am?</button></td>

<table class="table table-condensed table-hover">
    <tr>
        <th>Rank</th>
        <th>Avatar</th>
        <th>Username</th>
        <th>Experience Points</th>
    </tr>
    @{int counter = 1;}
    @foreach (var player in Model)
    {
        <tr>
            <td>@counter</td>
            <td><img class="mini-avatar" src="@player.AvatarURL" , alt="avatar" /></td>
            <td>@player.Username</td>
            <td>@player.XP</td>

            @{counter++;}
        </tr>
    }
</table>